#!/usr/bin/env python3
"""
Скрипт для автоматической сборки ConfigMap из конфигураций Config Server
Просто читает файлы из директории config и формирует ConfigMap
"""

import os
import re
from pathlib import Path
from datetime import datetime

# Директория где находится скрипт
SCRIPT_DIR = Path(__file__).parent.absolute()
# Корень проекта (на два уровня выше от helms/config-maker)
PROJECT_ROOT = SCRIPT_DIR.parent.parent  # HW07

# Относительные пути от корня проекта
CONFIG_SOURCE_DIR = PROJECT_ROOT / "config-service" / "src" / "main" / "resources" / "config"
CONFIG_TEMPLATE_PATH = PROJECT_ROOT / "helms" / "hw07-config-service" / "templates" / "config" / "config-server-configs.yaml"
OUTPUT_PATH = PROJECT_ROOT / "helms" / "hw07-config-service" / "templates" / "config" / "config-server-configs.generated.yaml"

# Вывод информации о путях для отладки
print(f"📁 Директория скрипта: {SCRIPT_DIR}")
print(f"📁 Корень проекта: {PROJECT_ROOT}")
print(f"📁 Источник конфигов: {CONFIG_SOURCE_DIR}")
print(f"📁 Шаблон Helm: {CONFIG_TEMPLATE_PATH}")
print("=" * 60)

def read_config_file(config_path):
    """Читает конфигурационный файл."""
    try:
        with open(config_path, 'r', encoding='utf-8') as f:
            return f.read()
    except UnicodeDecodeError:
        # Пробуем другие кодировки
        try:
            with open(config_path, 'r', encoding='cp1251') as f:
                return f.read()
        except:
            with open(config_path, 'r', encoding='latin-1') as f:
                return f.read()

def find_config_files():
    """Находит все конфигурационные файлы в директории config."""
    config_files = {}

    if not CONFIG_SOURCE_DIR.exists():
        print(f"❌ Директория не найдена: {CONFIG_SOURCE_DIR}")
        return config_files

    # Ищем все YAML/yml файлы
    for file_path in CONFIG_SOURCE_DIR.rglob("*.yaml"):
        relative_path = file_path.relative_to(CONFIG_SOURCE_DIR)
        config_files[str(relative_path)] = file_path

    for file_path in CONFIG_SOURCE_DIR.rglob("*.yml"):
        relative_path = file_path.relative_to(CONFIG_SOURCE_DIR)
        config_files[str(relative_path)] = file_path

    # Ищем все properties файлы (на случай если они есть)
    for file_path in CONFIG_SOURCE_DIR.rglob("*.properties"):
        relative_path = file_path.relative_to(CONFIG_SOURCE_DIR)
        config_files[str(relative_path)] = file_path

    return config_files

def generate_configmap():
    """Генерирует ConfigMap YAML файл."""

    print(f"📂 Ищем конфигурации в: {CONFIG_SOURCE_DIR}")

    # Проверяем существование директории
    if not CONFIG_SOURCE_DIR.exists():
        print(f"❌ Директория не существует!")
        print(f"   Создайте директорию: {CONFIG_SOURCE_DIR}")
        return False

    # Загружаем существующий шаблон для получения метаданных
    template_metadata = """  name: config-server-configs
  labels:
    {{- include "hw07-config-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: config-service"""

    if CONFIG_TEMPLATE_PATH.exists():
        try:
            with open(CONFIG_TEMPLATE_PATH, 'r', encoding='utf-8') as f:
                template_content = f.read()

            # Извлекаем метаданные из шаблона
            metadata_match = re.search(r'apiVersion: v1\nkind: ConfigMap\nmetadata:\n(.*?)\ndata:', template_content, re.DOTALL)

            if metadata_match:
                template_metadata = metadata_match.group(1).rstrip()
        except Exception as e:
            print(f"⚠️  Не удалось прочитать шаблон: {e}")

    # Находим все конфигурационные файлы
    config_files = find_config_files()

    if not config_files:
        print("❌ Не найдено конфигурационных файлов!")
        print(f"   Проверьте наличие файлов в: {CONFIG_SOURCE_DIR}")
        return False

    # Собираем конфигурации
    config_data = {}

    # Обрабатываем все файлы
    for relative_path, file_path in sorted(config_files.items()):
        print(f"📄 Читаем: {relative_path}")
        content = read_config_file(file_path)
        if content:
            config_data[relative_path] = content
        else:
            print(f"  ⚠️  Файл пустой или нечитаем")

    # Генерируем YAML
    yaml_output = f"""# Generated by build-config.py on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
# DO NOT EDIT THIS FILE DIRECTLY - edit source configs in:
# {CONFIG_SOURCE_DIR}
apiVersion: v1
kind: ConfigMap
metadata:
{template_metadata}
data:
"""

    # Добавляем конфигурации в формате ключ: | многострочное значение
    for config_name, config_content in sorted(config_data.items()):
        # Экранируем символы для YAML
        if config_content:
            yaml_output += f"  {config_name}: |\n"
            for line in config_content.split('\n'):
                yaml_output += f"    {line}\n"
            yaml_output += "\n"

    # Создаем директорию если не существует
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    # Сохраняем результат
    with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
        f.write(yaml_output)

    print(f"\n✅ Конфигурация успешно сгенерирована!")
    print(f"📁 Файл: {OUTPUT_PATH}")
    print(f"📊 Обработано файлов: {len(config_data)}")

    # Показываем список обработанных файлов
    print(f"\n📋 Список конфигураций:")
    for config_name in sorted(config_data.keys()):
        print(f"  • {config_name}")

    return True

def create_backup():
    """Создает резервную копию текущего файла конфигурации."""
    if CONFIG_TEMPLATE_PATH.exists():
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        backup_path = CONFIG_TEMPLATE_PATH.with_name(f"{CONFIG_TEMPLATE_PATH.stem}.backup_{timestamp}.yaml")
        try:
            with open(CONFIG_TEMPLATE_PATH, 'r', encoding='utf-8') as src, \
                    open(backup_path, 'w', encoding='utf-8') as dst:
                dst.write(src.read())
            print(f"📂 Создана резервная копия: {backup_path}")
            return True
        except Exception as e:
            print(f"⚠️  Не удалось создать резервную копию: {e}")
            return False
    return False

def main():
    print("🔧 Генератор конфигураций для Config Server")
    print("=" * 50)
    print(f"Источник: {CONFIG_SOURCE_DIR}")
    print(f"Цель:     {CONFIG_TEMPLATE_PATH}")
    print("=" * 50)

    # Проверяем директорию с конфигами
    if not CONFIG_SOURCE_DIR.exists():
        print(f"\n❌ Директория с конфигурациями не найдена!")
        print(f"Создайте директорию и добавьте файлы конфигураций:")
        print(f"  mkdir -p \"{CONFIG_SOURCE_DIR}\"")
        return

    # Создаем резервную копию
    create_backup()

    # Генерируем новую конфигурацию
    success = generate_configmap()

    if not success:
        return

    # Предлагаем обновить основной файл
    print(f"\n🔄 Хотите обновить основной файл конфигурации?")
    print(f"   Основной файл: {CONFIG_TEMPLATE_PATH}")
    print(f"   Сгенерированный: {OUTPUT_PATH}")
    choice = input("   (y/n): ").strip().lower()

    if choice == 'y':
        try:
            with open(OUTPUT_PATH, 'r', encoding='utf-8') as src, \
                    open(CONFIG_TEMPLATE_PATH, 'w', encoding='utf-8') as dst:
                dst.write(src.read())
            print(f"✅ Основной файл обновлен: {CONFIG_TEMPLATE_PATH}")
        except Exception as e:
            print(f"❌ Не удалось обновить файл: {e}")
    else:
        print(f"ℹ️  Основной файл не изменен.")
        print(f"   Новый конфиг сохранен в: {OUTPUT_PATH}")

if __name__ == "__main__":
    main()