/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.10.2/samples
 */
import com.diffplug.gradle.spotless.SpotlessExtension
import fr.brouillard.oss.gradle.plugins.JGitverPluginExtension
import io.spring.gradle.dependencymanagement.dsl.DependencyManagementExtension
import name.remal.gradle_plugins.sonarlint.SonarLintExtension
import org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES

plugins {
    idea  // Поддержка IntelliJ IDEA
    id("fr.brouillard.oss.gradle.jgitver")      // Автоматическое версионирование через Git
    id("io.spring.dependency-management")       // Управление зависимостями (аналог Maven BOM)
    id("org.springframework.boot") apply false  // Spring Boot, но не применяем к корню
    id("name.remal.sonarlint") apply false      // Статический анализ кода
    id("com.diffplug.spotless") apply false     // Форматирование кода
    id("checkstyle")                // Проверка стиля кода
}


// Общие настройки для всех проектов
allprojects {
    group = "ru.vvsem"  // Аналог <groupId> в Maven

    repositories {
        mavenLocal()    // Локальный Maven репозиторий (~/.m2)
        mavenCentral()  // Maven Central
    }
    // Управление зависимостями (аналог Maven Dependency Management)
    val springCloudVersion: String by project
    val logbackEncoder: String by project
    apply(plugin = "io.spring.dependency-management")
    dependencyManagement {
        dependencies {
            imports {
                // Импортируем BOM'ы (аналог <dependencyManagement> в Maven)
                mavenBom(BOM_COORDINATES)  // Spring Boot BOM
                mavenBom("org.springframework.cloud:spring-cloud-dependencies:$springCloudVersion")
            }
            dependency("net.logstash.logback:logstash-logback-encoder:$logbackEncoder")
        }
    }
}

// Настройки для всех подпроектов (микросервисов)
subprojects {
    // Применяем плагины ко всем подпроектам
    apply(plugin = "org.springframework.boot")
    apply(plugin = "java")
    apply(plugin = "com.diffplug.spotless")
    apply(plugin = "name.remal.sonarlint")
    apply(plugin = "fr.brouillard.oss.gradle.jgitver")
    apply(plugin = "checkstyle")

//    // Настройка Java (аналог maven-compiler-plugin)
//    extensions.configure<JavaPluginExtension> {
//        sourceCompatibility = JavaVersion.VERSION_21
//        targetCompatibility = JavaVersion.VERSION_21
//    }
    configure<JavaPluginExtension> {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    // Настройки компиляции
    tasks.withType<JavaCompile> {
        options.encoding = "UTF-8"
        options.compilerArgs.addAll(listOf("-Xlint:all,-serial,-processing"))
        dependsOn("spotlessApply") // Форматируем код перед компиляцией
    }

    // Настройка Checkstyle
    configure<CheckstyleExtension> {
        val checkstylePluginVersion = rootProject.property("checkstyle.version") as String
        val checkstyleConfigUrl = rootProject.property("checkstyle.config.url") as String
        toolVersion = checkstylePluginVersion  // Используем версию из gradle.properties
        config = resources.text.fromUri(checkstyleConfigUrl)
        maxErrors = 0
        maxWarnings = 0
        isIgnoreFailures = false
    }



    configure<SpotlessExtension> {
        java {
            palantirJavaFormat("2.38.0")  // Автоматическое форматирование кода
        }
    }

    configure<SonarLintExtension> {
        nodeJs {
            detectNodeJs = false
            logNodeJsNotFound = false
        }
    }


    // Настройки тестов
    tasks.withType<Test> {
        useJUnitPlatform()  // Используем JUnit 5 (аналог surefire-plugin в Maven)
        testLogging.showExceptions = true
        reports {
            junitXml.required.set(true) // XML отчеты для CI/CD
            html.required.set(true)     // HTML отчеты
        }
    }

    // Автоматическое версионирование
    //автоматически генерирует версии на основе Git тегов и коммитов.
    extensions.configure<JGitverPluginExtension> {
        strategy("PATTERN")
        nonQualifierBranches("main,master")
        tagVersionPattern("\${v}\${<meta.DIRTY_TEXT}")
        versionPattern(
            "\${v}\${<meta.COMMIT_DISTANCE}\${<meta.GIT_SHA1_8}" +
                    "\${<meta.QUALIFIED_BRANCH_NAME}\${<meta.DIRTY_TEXT}-SNAPSHOT"
        )
    }



}

tasks {
    register("printManagedVersions") {
        doLast {
            project.extensions.getByType<DependencyManagementExtension>()
                .managedVersions
                .toSortedMap()
                .map { "${it.key}:${it.value}" }
                .forEach(::println)
        }
    }
}