image:
  tag: "0.0.0-74-SNAPSHOT"

app:
  services:
    configService:
      host: hw07-config-service
      port: 8888
    userService:
      host: hw07-user-service
      port: 8082
    authService:
      host: hw07-auth-service
      port: 8081
    apiGateway:
      host: api-gateway
      port: 8079
    billingService:
      host: hw07-billing-service
      port: 8083
    orderService:
      host: hw07-order-service
      port: 8084
    notificationService:
      host: hw07-notification-service
      port: 8085