prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}

#    podMonitorNamespaceSelector: {}  # пустой объект выбирает все неймспейсы
#    serviceMonitorNamespaceSelector: {}  # пустой объект выбирает все неймспейсы