prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    # Исправьте эти строки:
    podMonitorNamespaceSelector: {}  # пустой объект выбирает все неймспейсы
    serviceMonitorNamespaceSelector: {}  # пустой объект выбирает все неймспейсы