package com.microservices.warehouse.model;

public enum EventType {
    WAREHOUSE_RESERVATION_COMPLETED,
    WAREHOUSE_RESERVATION_FAILED,

    WAREHOUSE_RESERVATION_COMPENSATION_COMPLETED,
    WAREHOUSE_RESERVATION_COMPENSATION_FAILED;
}
