nameOverride: ""

fullnameOverride: ""

postgresql:
  enabled: true
  fullnameOverride: hw09-postgresql
  auth:
    username: app_user
    database: microservices_db
    existingSecret: postgresql-secret
    secretKeys:
      adminPasswordKey: postgres-admin-password
      userPasswordKey: postgres-password

secrets:
  postgresAdminPassword: ""
  postgresPassword: ""