package com.microservices.order.model;

public enum EventType {
    ORDER_CREATED,
    ORDER_CANCELLING,
    ORDER_CANCELED,

    // Payment
    PAYMENT_COMPLETED,
    PAYMENT_REQUESTED,
    PAYMENT_REFUNDED,
    PAYMENT_FAILED,
    PAYMENT_COMPENSATION_COMPLETED,
    PAYMENT_COMPENSATION_FAILED,

    // Warehouse
    WAREHOUSE_RESERVED,
    WAREHOUSE_REQUESTED,
    WAREHOUSE_CANCELED,
    WAREHOUSE_RESERVATION_FAILED,

    // Delivery
    DELIVERY_SCHEDULED,
    DELIVERY_REQUESTED,
    DELIVERY_CANCELLED,
    DELIVERY_FAILED,
    NOTIFICATION_SENT,
    SAGA_COMPLETED,
    SAGA_COMPENSATED
}
