package com.microservices.order.model;

public enum EventType {
    ORDER_CREATED,
    ORDER_FAILED,
    PAYMENT_COMPLETED,
    PAYMENT_REQUESTED,
    PAYMENT_REFUNDED,
    PAYMENT_FAILED,
    WAREHOUSE_RESERVED,
    WAREHOUSE_REQUESTED,
    WAREHOUSE_CANCELED,
    WAREHOUSE_RESERVATION_FAILED,
    DELIVERY_SCHEDULED,
    DELIVERY_REQUESTED,
    DELIVERY_FAILED,
    NOTIFICATION_SENT,
    SAGA_COMPLETED,
    SAGA_COMPENSATED
}
