openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8084
  description: Generated server url
paths:
  /orders:
    get:
      tags:
      - order-controller
      operationId: getOrders
      parameters:
      - name: X-User-Id
        in: header
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/com.microservices.order.dto.OrderResponse"
    post:
      tags:
      - order-controller
      operationId: create
      parameters:
      - name: X-User-Id
        in: header
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/com.microservices.order.dto.CreateOrderRequest"
        required: true
      responses:
        "201":
          description: Created
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/com.microservices.order.dto.OrderResponse"
  /springwolf/ui-config:
    get:
      tags:
      - ui-config-controller
      operationId: getUiConfig
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/io.github.springwolf.core.controller.UiConfigController.UiConfig"
  /springwolf/docs:
    get:
      tags:
      - async-api-controller
      operationId: asyncApiYaml
      parameters: []
      responses:
        "200":
          description: OK
          content:
            application/yaml:
              schema:
                type: string
            application/json:
              schema:
                type: string
  /springwolf/docs/{group}:
    get:
      tags:
      - async-api-controller
      operationId: asyncApiYaml_1
      parameters:
      - name: group
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/yaml:
              schema:
                type: string
            application/json:
              schema:
                type: string
  /springwolf/docs.yaml:
    get:
      tags:
      - async-api-controller
      operationId: asyncApiYaml_2
      parameters: []
      responses:
        "200":
          description: OK
          content:
            application/yaml:
              schema:
                type: string
  /springwolf/docs.json:
    get:
      tags:
      - async-api-controller
      operationId: asyncApiJson
      parameters: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
  /orders/{orderId}:
    get:
      tags:
      - order-controller
      operationId: getOrder
      parameters:
      - name: X-User-Id
        in: header
        required: true
        schema:
          type: string
          format: uuid
      - name: orderId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/com.microservices.order.dto.OrderResponse"
components:
  schemas:
    com.microservices.order.dto.CreateOrderRequest:
      type: object
      properties:
        price:
          type: number
          minimum: 0.01
      title: CreateOrderRequest
    com.microservices.order.dto.OrderResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        price:
          type: number
        status:
          type: string
          enum:
          - PAID
          - FAILED
          - PENDING
        createdAt:
          type: string
          format: date-time
      title: OrderResponse
    io.github.springwolf.core.controller.UiConfigController.UiConfig:
      type: object
      properties:
        initialConfig:
          $ref: "#/components/schemas/io.github.springwolf.core.controller.UiConfigController.UiConfig.InitialConfig"
        groups:
          type: array
          items:
            $ref: "#/components/schemas/io.github.springwolf.core.controller.UiConfigController.UiConfig.UiConfigGroup"
      title: UiConfig
    io.github.springwolf.core.controller.UiConfigController.UiConfig.InitialConfig:
      type: object
      properties:
        showBindings:
          type: boolean
        showHeaders:
          type: boolean
      title: InitialConfig
    io.github.springwolf.core.controller.UiConfigController.UiConfig.UiConfigGroup:
      type: object
      properties:
        name:
          type: string
      title: UiConfigGroup
