openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8082
  description: Generated server url
paths:
  /users/me:
    get:
      tags:
      - user-controller
      operationId: getMyProfile
      parameters:
      - name: X-User-Id
        in: header
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProfileResponse"
    put:
      tags:
      - user-controller
      operationId: updateMyProfile
      parameters:
      - name: X-User-Id
        in: header
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProfileRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProfileResponse"
    delete:
      tags:
      - user-controller
      operationId: deactivateMyProfile
      parameters:
      - name: X-User-Id
        in: header
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
  /internal/profile:
    post:
      tags:
      - internal-controller
      operationId: createProfileInternal
      parameters:
      - name: X-User-Id
        in: header
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProfileRequest"
        required: true
      responses:
        "201":
          description: Created
  /users/{userId}:
    get:
      tags:
      - user-controller
      operationId: getProfile
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: X-User-Id
        in: header
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProfileResponse"
  /users/username/{username}:
    get:
      tags:
      - user-controller
      operationId: getProfileByUsername
      parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
      - name: X-User-Id
        in: header
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProfileResponse"
  /internal/me:
    get:
      tags:
      - internal-controller
      operationId: getMyProfile_1
      parameters:
      - name: X-User-Id
        in: header
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProfileResponse"
components:
  schemas:
    UpdateProfileRequest:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phone:
          type: string
        dateOfBirth:
          type: string
          format: date
    ProfileResponse:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phone:
          type: string
        dateOfBirth:
          type: string
          format: date
        status:
          type: string
          enum:
          - ACTIVE
          - INACTIVE
          - SUSPENDED
    CreateProfileRequest:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        username:
          type: string
          minLength: 1
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
          minLength: 1
        phone:
          type: string
        dateOfBirth:
          type: string
          format: date
      required:
      - email
      - userId
      - username
