server:
  port: 8083

spring:
  application:
    name: warehouse-service
  config:
    import: optional:configserver:http://${CONFIG_SERVICE_HOST:config-service}:${CONFIG_SERVICE_PORT:8888}
  cloud:
    config:
      enabled: ${CONFIG_SERVICE_ENABLED:true}
      fail-fast: true

logging:
  level:
    com.microservices.billing: DEBUG

