openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8081
  description: Generated server url
paths:
  /internal/validate:
    post:
      tags:
      - internal-controller
      operationId: validateToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthValidateTokenRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthTokenValidationResponse"
  /auth/validate:
    post:
      tags:
      - auth-controller
      operationId: validateToken_1
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthValidateTokenRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: boolean
  /auth/register:
    post:
      tags:
      - auth-controller
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRegisterRequest"
        required: true
      responses:
        "201":
          description: Created
  /auth/refresh:
    post:
      tags:
      - auth-controller
      operationId: refreshToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRefreshTokenRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthTokenResponse"
  /auth/logout:
    post:
      tags:
      - auth-controller
      operationId: logout
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRefreshTokenRequest"
        required: true
      responses:
        "204":
          description: No Content
  /auth/login:
    post:
      tags:
      - auth-controller
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthLoginRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AuthTokenResponse"
components:
  schemas:
    AuthValidateTokenRequest:
      type: object
      description: Запрос на валидацию токена
      properties:
        token:
          type: string
          maxLength: 2147483647
          minLength: 1
      required:
      - token
      title: AuthValidateTokenRequest
    AuthTokenValidationResponse:
      type: object
      description: Ответ валидации токена
      properties:
        valid:
          type: boolean
        userId:
          type: string
        username:
          type: string
        roles:
          type: array
          items:
            type: string
          uniqueItems: true
        tokenType:
          type: string
        error:
          type: string
      title: AuthTokenValidationResponse
    AuthRegisterRequest:
      type: object
      description: Запрос регистрации пользователя
      properties:
        email:
          type: string
          format: email
          maxLength: 2147483647
          minLength: 1
        username:
          type: string
          maxLength: 50
          minLength: 3
        password:
          type: string
          maxLength: 2147483647
          minLength: 8
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
          maxLength: 30
          minLength: 0
      required:
      - email
      - password
      - username
      title: AuthRegisterRequest
    AuthRefreshTokenRequest:
      type: object
      description: Запрос обновления токена
      properties:
        refreshToken:
          type: string
          maxLength: 2147483647
          minLength: 1
      required:
      - refreshToken
      title: AuthRefreshTokenRequest
    AuthTokenResponse:
      type: object
      description: Ответ с токенами
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        tokenType:
          type: string
        expiresIn:
          type: integer
          format: int64
      title: AuthTokenResponse
    AuthLoginRequest:
      type: object
      description: Запрос авторизации
      properties:
        login:
          type: string
          maxLength: 2147483647
          minLength: 1
        password:
          type: string
          maxLength: 2147483647
          minLength: 1
      required:
      - login
      - password
      title: AuthLoginRequest
