openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8083
  description: Generated server url
paths:
  /internal/order:
    post:
      tags:
      - internal-controller
      operationId: withdraw
      parameters:
      - name: X-User-Id
        in: header
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BillingOrderRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BillingBalanceResponse"
  /billing/accounts/withdraw:
    post:
      tags:
      - billing-controller
      operationId: withdraw_1
      parameters:
      - name: X-User-Id
        in: header
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BillingAmountRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BillingBalanceResponse"
  /billing/accounts/deposit:
    post:
      tags:
      - billing-controller
      operationId: deposit
      parameters:
      - name: X-User-Id
        in: header
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BillingAmountRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BillingBalanceResponse"
  /billing/accounts/balance:
    get:
      tags:
      - billing-controller
      operationId: balance
      parameters:
      - name: X-User-Id
        in: header
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BillingBalanceResponse"
components:
  schemas:
    BillingOrderRequest:
      type: object
      description: Запрос для операций с заказами в биллинге
      properties:
        userId:
          type: string
          format: uuid
        orderId:
          type: string
          format: uuid
        price:
          type: number
          minimum: 0.01
      title: BillingOrderRequest
    BillingBalanceResponse:
      type: object
      description: Ответ с балансом пользователя
      properties:
        userId:
          type: string
          format: uuid
        balance:
          type: number
      title: BillingBalanceResponse
    BillingAmountRequest:
      type: object
      description: Запрос с суммой операции
      properties:
        amount:
          type: number
          minimum: 0.01
      required:
      - amount
      title: BillingAmountRequest
