package com.microservices.delivery.model;

public enum EventType {
    DELIVERY_RESERVATION_COMPLETED,
    DELIVERY_RESERVATION_FAILED,

    DELIVERY_RESERVATION_COMPENSATION_COMPLETED,
    DELIVERY_RESERVATION_COMPENSATION_FAILED
}
