{
 "title": "HW05",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"hw05-service-user\", status=~\"5..\"}[2m]))\r\n/\r\nsum(rate(http_server_requests_seconds_count{application=\"hw05-service-user\"}[2m])) \r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Ingress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ exported_service=\"hw05-service-user\", status=~\"5..\"}[2m])) by (ingress, service)\r\n/\r\nsum(rate(nginx_ingress_controller_requests{ exported_service=\"hw05-service-user\",  }[2m])) by (ingress, service)\r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate on service",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"hw05-service-user\", status=~\"5..\"}[2m])) \r\n/\r\nsum(rate(http_server_requests_seconds_count{application=\"hw05-service-user\"}[2m])) \r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate от Nginx",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ exported_service=\"hw05-service-user\" , status=~\"5..\"}[5m])) by ( ingress, service)\r\n/\r\nsum(rate(nginx_ingress_controller_requests{ exported_service=\"hw05-service-user\" , }[5m])) by ( ingress, service)\r\n* 100",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Latency (0.5)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, uri, method) (rate(http_server_requests_seconds_bucket{application=\"hw05-service-user\"}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (0.95)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, uri, method) (rate(http_server_requests_seconds_bucket{application=\"hw05-service-user\"}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (0.99)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, uri, method) (rate(http_server_requests_seconds_bucket{application=\"hw05-service-user\"}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (MAX)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "max(http_server_requests_seconds_max{application=\"hw05-service-user\"}) by (uri, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS (all)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 7, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"hw05-service-user\"}[2m])) by (uri, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "RPS - INGRESS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ exported_service=\"hw05-service-user\" }[5m])) by ( exported_service)",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "Latency (0.5/0.95/0.99) - INGRESS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \r\n  sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{}[2m])) \r\n  by (le, ingress, exported_service)\r\n) ",
     "legendFormat": "Latency 0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{}[2m])) by (le, ingress, exported_service))",
     "legendFormat": "Latency 0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{}[2m])) by (le, ingress, exported_service))",
     "legendFormat": "Latency 0.99"
    }
   ]
  },
  { "title": "Pods statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Memory Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  container_memory_working_set_bytes{\r\n    pod=~\"hw05-service-user-.*\"\r\n  }\r\n) by (pod) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Limits",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum(container_memory_working_set_bytes{pod=~\"hw05-service-user-.*\",}) by (pod) \r\n/ sum(kube_pod_container_resource_limits{pod=~\"hw05-service-user-.*\", resource=\"memory\"}) by (pod) ) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU uses",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"hw05-service-user-.*\"}[2m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"hw05-service-user-.*\"}[2m])) by (pod) / sum(kube_pod_container_resource_limits{pod=~\"hw05-service-user-.*\", resource=\"cpu\"}) by (pod) ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Transactions per seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"users_db\"}[2m]) + rate(pg_stat_database_xact_rollback{datname=\"users_db\"}[2m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "% rollback",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_xact_rollback{datname=\"users_db\"} / (pg_stat_database_xact_commit{datname=\"users_db\"} + pg_stat_database_xact_rollback{datname=\"users_db\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"users_db\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}