apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservices-app.fullname" . }}-postgresql-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservices-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  password: {{ .Values.postgresql.password }}

