apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-configs
  labels:
    {{- include "hw07-config-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: config-service
data:
  # Общий конфиг для всех сервисов
  application.yml: |
    spring:
      output:
        ansi:
          enabled: ALWAYS

    server:
      error:
        whitelabel:
          enabled: false


    # Настройки сервисов
    app:
      services:
        user-service:
          url: http://${USER_SERVICE_HOST:localhost}:${USER_SERVICE_PORT:8082}
          endpoints:
            profile: /internal/profile
            me: /internal/me

        auth-service:
          url: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8081}
          endpoints:
            validate: /internal/validate

        billing-service:
          url: http://${BILLING_SERVICE_HOST:localhost}:${BILLING_SERVICE_PORT:8083}
          endpoints:
            order: /internal/order


        order-service:
          url: http://${ORDER_SERVICE_HOST:localhost}:${ORDER_SERVICE_PORT:8084}

        notification-service:
          url: http://${NOTIFICATION_SERVICE_HOST:localhost}:${NOTIFICATION_SERVICE_PORT:8085}

      security:
        inter-service:
          secret: ${INTER_SERVICE_SECRET:inter-service-secret-1gas+1!sda2ga52111}
          user-id-header: X-User-Id
          roles-header: X-Roles
          service-secret-header: X-Service-Secret
          service-name-header: X-Service-Name
          request-id-header: X-Request-Id
          token-header: Authorization
          token-prefix: "Bearer "

    rest:
      client:
        connect-timeout: 5s
        read-timeout: 10s


    # Actuator конфигурация
    management:
      tracing:
        sampling:
          probability: 1.0

      endpoint:
        env:
          show-values: ALWAYS
        configprops:
          access: read-only
          show-values: ALWAYS
        health:
          access: read-only
          probes:
            enabled: true
          show-details: ALWAYS
          show-components: ALWAYS
        metrics:
          access: read-only
        logfile:
          access: read-only
        prometheus:
          access: read-only
        refresh:
          access: read-only
        gateway:
          access: read-only


      endpoints:
        web:
          exposure:
            include:
              - configprops
              - health
              - info
              - logfile
              - liquibase
              - metrics
              - prometheus
              - refresh
              - gateway
              - env
          base-path: /actuator

      # Экспорт метрик в Prometheus
      prometheus:
        metrics:
          export:
            enabled: true
            step: 1m
            descriptions: true

      observations:
        http:
          server:
            requests:
              name: http.server.requests

      # Метрики конфигурация
      metrics:
        enable:
          http: true
          jvm: true
          logback: true
          processor: true
          system: true
        distribution:
          slo:
            http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms, 600ms, 800ms
          percentiles-histogram:
            http.server.requests: true

        # Тэги для метрик
        tags:
          application: ${spring.application.name}
          region: local


    # SpringDoc (OpenAPI) конфигурация - исправленный путь
    springdoc:
      api-docs:
        path: /v3/api-docs
      swagger-ui:
        path: /swagger-ui.html
        enabled: true
      messages:
        baseName: messages
        encoding: UTF-8
        fallbackToSystemLocale: false
        use-code-as-default-message: true
      enable-hateoas: false
      show-actuator: true

    logging:
      level:
        #    com.microservices.auth.filter.MdcFilter: DEBUG

        # Spring Security логгирование
        org.springframework.security: INFO
        org.springframework.security.web: INFO
        org.springframework.security.config: INFO
        org.springframework.security.web.FilterChainProxy: INFO

        #    # HTTP запросы
        #    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
        #    org.apache.coyote.http11: DEBUG
        #    org.springframework.web: INFO

        #     Фильтры
        #    com.microservices.user.filter: DEBUG

        # Hibernate/SQL
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

        # Мои пакеты
        com.microservices: DEBUG

        liquibase: INFO

        org.apache.coyote.http11.Http11InputBuffer: TRACE
      #    # или для embedded Tomcat:
      #    tomcat.util.http.parser: DEBUG

  # Конфиг для api-gateway
  api-gateway.yml: |
    server:
      port: 8079

    spring:
      application:
        name: api-gateway
      cloud:
        gateway:
          server:
            webflux:
              httpclient:
                connect-timeout: 1000
                response-timeout: 5s

              routes:
                # Billing-Service
                # Endpoints c авторизацией
                - id: billing-service
                  uri: http://${BILLING_SERVICE_HOST:localhost}:${BILLING_SERVICE_PORT:8083}
                  predicates:
                    - Path=/api/v1/billing/**
                  filters:
                    - StripPrefix=2
                    - name: JwtValidationFilter
                      args:
                        requireAuth: true

                # Order-Service
                # Endpoints c авторизацией
                - id: order-service
                  uri: http://${ORDER_SERVICE_HOST:localhost}:${ORDER_SERVICE_PORT:8084}
                  predicates:
                    - Path=/api/v1/orders/**
                  filters:
                    - StripPrefix=2
                    - name: JwtValidationFilter
                      args:
                        requireAuth: true

                # Notification-Service
                # Endpoints c авторизацией
                - id: notification-service
                  uri: http://${NOTIFICATION_SERVICE_HOST:localhost}:${NOTIFICATION_SERVICE_PORT:8085}
                  predicates:
                    - Path=/api/v1/notif/**
                  filters:
                    - StripPrefix=2
                    - name: JwtValidationFilter
                      args:
                        requireAuth: true

                # Auth-Service
                # Публичные Endpoints без авторизации
                - id: auth-service-public
                  uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8081}
                  predicates:
                    - Path=/api/v1/auth/register,/api/v1/auth/login,/api/v1/auth/refresh,/api/v1/auth/validate
                  filters:
                    - StripPrefix=2

                # Auth-Service
                # Endpoints c авторизацией
                - id: auth-service
                  uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8081}
                  predicates:
                    - Path=/api/v1/auth/**
                  filters:
                    - StripPrefix=2

                # Actuator — только для внутреннего доступа
                - id: auth-service-actuator
                  uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8081}
                  predicates:
                    - Path=/auth/actuator/**
                  filters:
                    - StripPrefix=1

                # User-Service
                # Публичные Endpoints c авторизацией
                - id: user-service
                  uri: http://${USER_SERVICE_HOST:localhost}:${USER_SERVICE_PORT:8082}
                  predicates:
                    - Path=/api/v1/users/**
                  filters:
                    - StripPrefix=2
                    - name: JwtValidationFilter
                      args:
                        requireAuth: true

                # Actuator — только для внутреннего доступа
                - id: user-service-actuator
                  uri: http://${USER_SERVICE_HOST:localhost}:${USER_SERVICE_PORT:8082}
                  predicates:
                    - Path=/users/actuator/**
                  filters:
                    - StripPrefix=1

                # Actuator для самого Gateway
                - id: api-gateway-actuator
                  uri: http://localhost:${server.port}  # самореференс
                  predicates:
                    - Path=/actuator/**

          # Глобальные настройки
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE


    # Настройки для JWT валидации
    gateway:
      auth:
        auth-service-url: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8081}
        validate-endpoint: /internal/validate
        cache-enabled: true
        cache-size: 1000
        cache-ttl: 300000

    # Логирование
    logging:
      level:
        com.microservices.gateway: DEBUG
        org.springframework.cloud.gateway: DEBUG
        org.springframework.web.server: DEBUG
        reactor.netty: DEBUG



  # Конфиг для auth-service
  auth-service.yml: |
    server:
      port: 8081

    spring:
      application:
        name: auth-service

      datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:microservices_db}
        username: ${DB_USER:postgres}
        password: ${DB_PASSWORD:postgres}
        driver-class-name: org.postgresql.Driver

      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            default_schema: auth

      liquibase:
        change-log: classpath:db/changelog/auth-service.db.changelog-master.xml
        default-schema: auth
        liquibase-schema: public

      kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka.kafka:9092}
        client-id: "auth-service-producer"
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
          security.protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_PLAINTEXT}
          sasl.mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
          sasl.jaas.config: ${KAFKA_JAAS_CONFIG:org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USER:user1}" password="${KAFKA_PASSWORD}";}

    # Настройки JWT
    jwt:
      secret: ${JWT_SECRET:mySuperSecretKeyForJWT256BitSignatureKey123!}
      access-token-expiration: 900000      # 15 минут в миллисекундах
      refresh-token-expiration: 604800000  # 7 дней в миллисекундах

    app:
      # Настройки Kafka
      kafka:
        topics:
          user-created: user.created




  # Конфиг для billing-service
  billing-service.yml: |
    server:
      port: 8083

    spring:
      application:
        name: billing-service
      datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:microservices_db}
        username: ${DB_USER:postgres}
        password: ${DB_PASSWORD:postgres}
        driver-class-name: org.postgresql.Driver

      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            default_schema: billing_service

      liquibase:
        change-log: classpath:db/changelog/billing-service.db.changelog-master.xml
        default-schema: billing_service
        liquibase-schema: public

      kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka.kafka:9092}

        properties:
          security.protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_PLAINTEXT}
          sasl.mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
          sasl.jaas.config: ${KAFKA_JAAS_CONFIG:org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USER:user1}" password="${KAFKA_PASSWORD}";}

        consumer:
          group-id: billing-service
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

          properties:
            spring.json.use.type.headers: false
            spring.json.value.default.type: com.microservices.billing.kafka.UserCreatedEvent
            spring.json.trusted.packages: "*"

        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    app:
      kafka:
        topics:
          user-created: user.created


  # Конфиг для notification-service
  notification-service.yml: |
    server:
      port: 8085

    spring:
      application:
        name: notification-service
      datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:microservices_db}
        username: ${DB_USER:postgres}
        password: ${DB_PASSWORD:postgres}
        driver-class-name: org.postgresql.Driver

      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            default_schema: notification_service

      liquibase:
        change-log: classpath:db/changelog/notification-service.db.changelog-master.xml
        default-schema: notification_service
        liquibase-schema: public

      kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka.kafka:9092}

        properties:
          security.protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_PLAINTEXT}
          sasl.mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
          sasl.jaas.config: ${KAFKA_JAAS_CONFIG:org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USER:user1}" password="${KAFKA_PASSWORD}";}

        consumer:
          group-id: notification-service
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

          properties:
            spring.json.use.type.headers: false
            spring.json.value.default.type: com.microservices.notification.kafka.OrderEvent
            spring.json.trusted.packages: "*"

    app:
      kafka:
        topics:
          order-events: order.events


  # Конфиг для order-service
  order-service.yml: |
    server:
      port: 8084

    spring:
      application:
        name: order-service
      datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:microservices_db}
        username: ${DB_USER:postgres}
        password: ${DB_PASSWORD:postgres}
        driver-class-name: org.postgresql.Driver

      jpa:
        hibernate:
          ddl-auto: validate
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            default_schema: order_service

      liquibase:
        change-log: classpath:db/changelog/order-service.db.changelog-master.xml
        default-schema: order_service
        liquibase-schema: public

      kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka.kafka:9092}

        properties:
          security.protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_PLAINTEXT}
          sasl.mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
          sasl.jaas.config: ${KAFKA_JAAS_CONFIG:org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USER:user1}" password="${KAFKA_PASSWORD}";}

        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    app:
      kafka:
        topics:
          order-events: order.events


  # Конфиг для user-service
  user-service.yml: |
    server:
      port: 8082

    spring:
      application:
        name: user-service
      datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:microservices_db}
        username: ${DB_USER:postgres}
        password: ${DB_PASSWORD:postgres}
        driver-class-name: org.postgresql.Driver

      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            default_schema: user_service

      liquibase:
        change-log: classpath:db/changelog/user-service.db.changelog-master.xml
        default-schema: user_service
        liquibase-schema: public