apiVersion: v2
name: hw04-service-user
description: A Helm chart for deploying hw04.service-user to Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

dependencies:
  - name: postgresql
    version: 18.1.13
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
    wait: true
    timeout: 300s