{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-secret
  labels:
      {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  postgres-password: {{ .Values.secrets.postgresPassword | required "secrets.postgresPassword is required" | b64enc }}
  password: {{ .Values.secrets.password | required "secrets.password is required" | b64enc }}
{{- end }}